development:
  adapter: postgresql
  encoding: unicode
  database: craftworkshub_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: craftworkshub_production
  host: localhost
  pool: 5
  username: postgres
  password: postgres


test:
  adapter: postgresql
  encoding: unicode
  database: craftworkshub_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres